apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-kubernetes
  template:
    metadata:
      labels:
        app: simple-kubernetes
    spec:
      containers:
        - name: simple-kubernetes
          image: devamuleya/simple-kubernetes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
