apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-kubernetes-app
  labels:
    app: simple-kubernetes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-kubernetes-app
  template:
    metadata:
      labels:
        app: simple-kubernetes-app
    spec:
      containers:
        - name: simple-kubernetes-app
          image: dworkspace1/simple-kubernetes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
